name: Generate and save SSH key

on:
  push:
    branches:
      - main

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SSH key pair
        run: |
          ssh-keygen -t rsa -b 4096 -C "shekhawatajit@hotmail.com" -f ssh_key -q -N ""
          echo "::set-output name=private_key::$(cat mykey)"

      - name: Save private key to GitHub secret
        uses: actions/core@v2
        with:
          secret: SSH_PRIVATE_KEY
          value: ${{ steps.generate-ssh-key.outputs.private_key }}
